const RESEARCH_SOURCES = [
  {
    name: 'Ganyan',
    url: 'https://github.com/fatihbozdag/Ganyan',
    type: 'Open-source racetrack system',
    lesson: '把 LightGBM ranker、Bayesian Plackett-Luce、Harville 组合概率和赛后 ledger 放在同一条链路里；同时用 ROI 回撤说明避免被小样本高派彩骗到。',
    borrow: 'Bayes/置信门槛、Harville 组合拆解、trip-wire、真实 ledger 复盘。',
  },
  {
    name: 'HKJC Horse-Racing ML Research Platform',
    url: 'https://github.com/stevw-repo/HKJC-Horse-Racing-ML-Research-Project',
    type: 'HKJC research sandbox',
    lesson: '本地研究平台应把 WIN/PLACE 概率、即时赔率、Kelly variants 和 honest backtest 分开记录。',
    borrow: '实时赔率融合、fractional Kelly sweep、风险上限、多资金规模回测。',
  },
  {
    name: 'neigh',
    url: 'https://github.com/larrysammii/neigh',
    type: 'HKJC typed data SDK',
    lesson: 'SpeedPRO current meeting JSON 比普通 racecard 更丰富，包含 sectional times、pace、fitness、comments、incidents 和 health notes。',
    borrow: 'SpeedPRO 特征导入、runner prior-run 展平、公共 unauthenticated 数据边界。',
    accessNote: '网页可读；2026-07-08 git ls-remote 暂时返回 repository not found，导入前需再次确认 clone/包管理器访问。',
  },
  {
    name: 'hkjc-api',
    url: 'https://github.com/Bobosky2005/hkjc-api',
    type: 'HKJC GraphQL odds/pool API',
    lesson: 'HKJC GraphQL 返回的 pmPools 不保证跟请求 oddsTypes 顺序一致，必须按 oddsType 匹配，避免 WIN/PLA/QIN/QPL 错位。',
    borrow: 'live odds/pool 抓取、防错归一化、GraphQL pool investment 字段。',
  },
  {
    name: 'HKJC Pool Money Calculator',
    url: 'https://github.com/Tang6133/hkjc-pool-tracker',
    type: 'Pari-mutuel pool-share methodology',
    lesson: '赔率不是全部；从 total investment、takeout 和 odds 反推每匹马/组合的资金份额，可以识别热门拥挤和冷门噪音。',
    borrow: 'WIN/PLA/QIN/QPL takeout、pool-share 估算、彩池结构特征。',
  },
  {
    name: 'HKJC Edge Lab',
    url: 'https://github.com/justinsuo/hkjc-edge-lab',
    type: 'NO-BET-by-default validation lab',
    lesson: '系统必须能诚实地得出 NO-GO：walk-forward、closing-line value、bootstrap CI 和 placebo 检验比单场命中更重要。',
    borrow: 'NO-BET 默认、CLV 复盘、bootstrap 置信区间、过拟合防线。',
  },
  {
    name: 'Hongkong-Horse-Racing-Prediction',
    url: 'https://github.com/anton-schwarberg/Hongkong-Horse-Racing-Prediction',
    type: 'HKJC historical ML pipeline',
    lesson: '严格时间切分、无未来数据泄漏、概率校准和字段重要性比单纯命中率更能反映模型质量。',
    borrow: '时间切分验证、校准曲线、SHAP/feature importance 思路、官方 rating/实时马表特征。',
  },
  {
    name: 'Keiba AI',
    url: 'https://github.com/tsukasaI/keiba-ai',
    type: 'JRA expected-value system',
    lesson: '下注入口应围绕 expected value：预测概率 × 赔率/派彩，未过阈值就 PASS。',
    borrow: 'EV 阈值、paper-trading loop、组合赔率验证后再实注。',
  },
  {
    name: 'HKJC Benter Engine',
    url: 'https://github.com/JonzieLo/hkjc-project',
    type: 'Parimutuel pricing and stacker research',
    lesson: '它提出 XGBoost/Cox/log-linear stacking、copula exotic pricing 和 drift-aware Kelly；但公开树没有数据、账本、测试或 LICENSE，README 指标与代码窗口/玩法语义存在不一致，不能视为已复现成绩。',
    borrow: '只借鉴实验问题：顺序概率 baseline ladder、依赖残差诊断、late-money drift、联合 payoff 风控；全部 clean-room 重做。',
    accessNote: '未知许可证；不复制代码。README 的 +6.63% ROI / TRI +35.99% 仅登记为作者声称，未经本地数据复现。',
  },
  {
    name: 'HKHorseRacing-Predictor',
    url: 'https://github.com/Tang6133/hkhorseracing-predictor',
    type: 'Public prediction archive',
    lesson: '即使模型私有，也可以公开 race-day prediction CSV、calibrated place probability 和产品化解释，方便长期复盘。',
    borrow: '预测归档、place ranking 展示、race-day intelligence UI。',
  },
  {
    name: 'tianxi-database',
    url: 'https://github.com/sleepingarhat/tianxi-database',
    type: 'HKJC data platform',
    lesson: '长期自动更新的数据平台可以作为覆盖率参照，帮助我们发现本地 SQLite 是否缺字段或缺赛季。',
    borrow: '2016-2026 覆盖率对账、每日数据健康检查、Elo-style 特征候选。',
  },
  {
    name: 'HK-Horse-Racing-Data-Scraper',
    url: 'https://github.com/j-csc/HK-Horse-Racing-Data-Scraper',
    type: 'HKJC scraper and data-schema reference',
    lesson: '老牌 HKJC 爬虫项目覆盖马匹、排位表、场地、兽医记录等页面，适合作为我们数据层补字段和爬虫容错的参考。',
    borrow: '兽医记录、racecard/排位表字段、HTML 解析边界、数据源覆盖审计。',
  },
  {
    name: 'hk-racing-quant',
    url: 'https://github.com/kokacheuk-del/hk-racing-quant',
    type: '+EV dashboard prototype',
    lesson: 'P_true vs P_market、+EV 卡片和 1/3 Kelly 展示方式很直观，但启发式权重要先经过我们本地回测。',
    borrow: '+EV UI、市场概率反推、Kelly stake explainability。',
  },
  {
    name: 'Horse-Racing-Prediction-HKJC',
    url: 'https://github.com/PeterLiuLiuLiu/Horse-Racing-Prediction-HKJC',
    type: 'HKJC + Benter-style prototype',
    lesson: 'Benter 的核心不是神秘规则，而是基本面模型 + 市场赔率修正 + 长期反馈。',
    borrow: 'Benter 路线：基本面概率、市场概率融合、特征数据库长期积累。',
  },
  {
    name: 'hkjc-analytics',
    url: 'https://github.com/snookerlivehk-elton/hkjc-analytics',
    type: 'Heuristic scoring and collector methodology reference',
    lesson: '它主要是启发式加权系统，不是可复现的训练模型；仓库没有数据库、模型产物或数值 benchmark，且赔率里程碑、SpeedPRO 和预测快照存在时间/覆盖风险。',
    borrow: '只做 clean-room 方法复现：不可变 as-of observations、严格赛前窗口、日期/场地/runner identity、收缩估计、recency、因子诊断和 pace 架构。',
    accessNote: '无许可证、无公开历史数据；不复制代码/权重/阈值，不把它登记为经验 benchmark。',
  },
];

const ALGORITHM_BORROWINGS = [
  {
    concept: 'Harville / Plackett-Luce 名次联合概率',
    status: 'active',
    userImpact: '位置、位置Q、连赢不再凭感觉拼组合，而是从同一组胜率推导组合命中率。',
    nextStep: '继续用真实派彩复盘，检查 QPL/连赢是否只是提高命中率但吞掉 ROI。',
  },
  {
    concept: '严格概率评分：Brier Score / Log Loss / 校准桶',
    status: 'active',
    userImpact: '前端成绩页能看到模型是否过度自信，避免只看中不中。',
    nextStep: '按场地、距离、赔率段拆校准，找到模型最容易高估的区间。',
  },
  {
    concept: 'Expected Value 入场线',
    status: 'active',
    userImpact: '推荐会显示期望 ROI、最低派彩，赔率不够就等或 PASS。',
    nextStep: '接入实时赔率/派彩后，把纸上建议转换成 T-30/T-10 的真实入场检查。',
  },
  {
    concept: 'Market odds 市场赔率融合与 favorite-longshot bias 修正',
    status: 'active',
    userImpact: '减少模型单边看好冷门导致整张票被一匹马拖死的风险。',
    nextStep: 'T-10 market-aware CatBoost 已完成历史比较；继续用 2026 prospective T-window 快照验证价格稳定性和现金 EV。',
  },
  {
    concept: 'Fractional Kelly + 资金/单马暴露上限',
    status: 'next',
    userImpact: '把 HK$10-100 的注码从固定规则升级成按 edge、方差和当天亏赢状态自适应。',
    nextStep: '做 Kelly fraction sweep，比较 0.1x、0.25x、0.5x Kelly 在历史回测里的最大回撤。',
  },
  {
    concept: 'Bayesian skip-gate / trip-wire',
    status: 'active',
    userImpact: '模型信心异常或数据质量异常时自动降低建议强度，宁可错过也不硬买。',
    nextStep: '90 日已结算信心基线、模型分歧、校准漂移和临场市场缺口已进入保护闸；继续用 prospective 数据校准阈值。',
  },
  {
    concept: 'Pool money / takeout / crowding features',
    status: 'active',
    userImpact: '不只看赔率高低，还看某匹马或组合是否被资金过度拥挤，减少追热门和错买低价值组合。',
    nextStep: '特征与 SQLite 读取链路已完成；继续积累 2026 T-window pool snapshots 后评估增益。',
  },
  {
    concept: 'SpeedPRO sectional / pace / fitness 特征',
    status: 'active',
    userImpact: '模型能解释步速、末段、健康记录和事件评论，而不是只靠历史名次和骑练统计。',
    nextStep: '本地 optional importer 已覆盖当前 5 个 meeting；继续回补有可信赛前时间戳的历史快照，再做同 cohort holdout 对比。',
  },
  {
    concept: 'NO-BET default + Closing Line Value 守门',
    status: 'active',
    userImpact: '模型没证明能赢 closing line 时，前端主动显示“不下注/只纸上观察”，防止为了下注而下注。',
    nextStep: '不可变 prospective locks、CLV、slippage、drawdown、meeting-block bootstrap 和 placebo 已进入审计；继续积累 fresh forward cohort。',
  },
  {
    concept: 'LightGBM / LambdaRank / 条件 logit 模型族',
    status: 'active',
    userImpact: '这是下一代基础胜率模型候选，不会立刻拿来真实下注。',
    nextStep: 'no-market LightGBM 已按时间切分训练并导出 WIN/PLACE 概率；现金升级仍取决于独立 ROI 与 prospective market gate。',
  },
  {
    concept: 'SHAP / feature importance 解释层',
    status: 'research-only',
    userImpact: '以后能解释“为什么看好这匹马”：骑师、档位、路程、近绩还是市场赔率。',
    nextStep: '先补齐官方 rating、马重变化、档位、场地、步速等字段。',
  },
  {
    concept: 'Parimutuel stacker / copula exotic pricing',
    status: 'research-only',
    userImpact: '未来可研究三重彩等高赔率玩法，但必须先证明 final-dividend 回测没有 late-money 偏差。',
    nextStep: '只在 benchmark registry 里登记，不进入现金推荐；先做模拟和误差边界。',
  },
];

const FOLLOW_UP_ACTIONS = [
  {
    id: 'upcoming-racecard-preflight',
    priority: 'P0',
    status: 'partial',
    automationPhase: 'Phase A/D',
    title: '自动预加载未来赛程与排位表',
    sourceRefs: ['official HKJC fixture', 'official HKJC race card'],
    action: '每日巡检先运行公开 fixture/race-card refresh，再用 sync-db 把可验证的 upcoming races 写入本地私有 SQLite。',
    expectedOutcome: '新赛季排位表发布后无需人工导入，十分钟 race-day cycle 可直接接手 T-30/T-10/T-3 采集。',
    automationExecutable: true,
    evidence: [
      'hkjc-horse-model/src/hkjc-parser.js：fetchFixtureMeetings / fetchMeetingRaceCards 使用官方公开页面并校验本地赛场身份',
      'hkjc-horse-model/src/cli.js：refresh + sync-db 复用现有 upcoming 数据链路，不新增账号登录或第二套爬虫',
      'hkjc-parser and sqlite-store tests：排位表解析、upcoming 状态、settled authority 与幂等同步均有回归保护',
    ],
    remaining: [
      '当前休赛期 upcoming=0；待新赛季首份 race card 发布后完成一次真实预加载、身份校验和 SQLite 覆盖确认。',
      '现金状态保持 NO_BET；预加载只处理公开赛程和排位表，不访问 HKJC 会员账户。',
    ],
  },
  {
    id: 'live-snapshot-planner',
    priority: 'P0',
    status: 'implemented',
    automationPhase: 'Phase A',
    title: '实现 T-30/T-10/T-3 live snapshot planner',
    sourceRefs: ['hkjc-api', 'HKJC Horse-Racing ML Research Platform', 'hkjc-analytics'],
    action: '读取 SQLite upcoming races，判断当前 HKT 是否进入 due window，并触发 WIN/PLA/QIN/QPL 抓取。',
    expectedOutcome: '每天巡检能自动积累 2026 临场 odds/pool 数据，先 dry-run 后导入。',
    automationExecutable: true,
    evidence: [
      'hkjc-horse-model/src/live-snapshot-planner.js + live-market-due-snapshots.js',
      'live-snapshot-planner / live-market-due-snapshots / live-market-snapshot tests',
      'hkjc-analytics clean-room audit 后补上严格 post-time guard；开赛后的观察不会再被标成 T-3。',
    ],
    remaining: ['赛马日继续积累真实 2026 T-30/T-10/T-3 odds/pool snapshots；没有 due window 时不伪造数据。'],
  },
  {
    id: 'pool-money-features',
    priority: 'P0',
    status: 'implemented',
    automationPhase: 'Phase A/B',
    title: '把 pool money / takeout / crowding 写成市场特征',
    sourceRefs: ['HKJC Pool Money Calculator', 'hkjc-api'],
    action: '从 odds + total investment 估算单马和组合资金份额，进入 odds_snapshots/pool_snapshots 派生特征。',
    expectedOutcome: 'EV 过滤不只依赖赔率，也能识别 crowding 和低价值组合。',
    automationExecutable: false,
    evidence: [
      'hkjc-horse-model/src/pool-money-features.js',
      'pool-money-features and SQLite market-feature tests',
    ],
    remaining: ['等待足量 prospective T-window pool coverage 后，评估 crowding 特征的 holdout/forward lift。'],
  },
  {
    id: 'benchmark-registry-refresh',
    priority: 'P0',
    status: 'implemented',
    automationPhase: 'Phase B',
    title: '更新 external benchmark registry',
    sourceRefs: ['catowabisabi', 'jerrydaphantom', 'HKJC Edge Lab', 'HKJC Benter Engine'],
    action: '登记每个外部思路的数据需求、泄漏风险、指标、promotion gate 和现金模式限制。',
    expectedOutcome: 'Research Lab 能显示哪些外部方法已复现、哪些仍不能用于下注。',
    automationExecutable: false,
    evidence: [
      'hkjc-horse-model/src/model-benchmark-registry.js',
      'model-benchmark-registry tests and dashboard-safe snapshot projection',
    ],
    remaining: ['外部项目有新证据时更新 registry；不把第三方 headline 当成本地已验证成绩。'],
  },
  {
    id: 'speedpro-feature-importer',
    priority: 'P1',
    status: 'partial',
    automationPhase: 'Phase B',
    title: '设计 SpeedPRO sectional/pace/fitness 特征导入',
    sourceRefs: ['neigh', 'tianxi-database', 'hkjc-analytics'],
    action: '先做 schema 和无泄漏规则，再导入当前 meeting SpeedPRO，历史回补另列任务。',
    expectedOutcome: '基础模型能学习步速、末段、fitness、incident/comments 的滞后信号。',
    automationExecutable: true,
    evidence: [
      'hkjc-horse-model/src/speedpro-feature-importer.js + CLI optional --speedproRoot wiring',
      '真实本地缓存抽样：2026-07-01 至 2026-07-15 共 5 个 meeting、637/637 runner rows 可用',
      'fixture tests 覆盖赛前快照、当前场排除、派生 pace/sectional/fitness/incident/health 特征',
      '导入器校验 meeting date、venue、runner code 和 source update time；逐 runner 记录 sourceId/observedAt/identityMatched/observedBeforePost，并按 train/validation/holdout/prospective 分开报告覆盖率。',
    ],
    remaining: ['回补有可信赛前时间戳的 historical SpeedPRO 快照，并完成有/无 SpeedPRO 的同 cohort holdout 对比。'],
  },
  {
    id: 'no-bet-clv-gate',
    priority: 'P1',
    status: 'partial',
    automationPhase: 'Phase C',
    title: '加入 NO-BET default 与 CLV 守门',
    sourceRefs: ['HKJC Edge Lab', 'Ganyan'],
    action: '推荐审计增加 closing-line value、bootstrap CI、placebo；未过门槛时现金推荐降级为 paper-only。',
    expectedOutcome: '系统可以诚实地输出 NO BET，而不是每场硬给下注。',
    automationExecutable: true,
    evidence: [
      'value-betting-engine.js 的 PLAY/WATCH/PAPER/NO_BET fail-closed gate',
      'recommendation-audit tests覆盖 CLV、slippage、cash drawdown 与 paper ROI 分离',
      'prospective-locks.js + prospective-lock/prospective-settle CLI：T-30/T-10/T-3 不可变锁单、官方派彩结算、VOID、T-3 CLV、回撤与连败均从 SQLite 锁单重算',
    ],
    remaining: ['积累足量 prospective recommendation locks，并补 bootstrap CI 与 placebo 稳健性检验。'],
  },
  {
    id: 'market-aware-shadow-bridge',
    priority: 'P5',
    status: 'implemented',
    automationPhase: 'Phase D',
    title: '接通 market-aware SHADOW scoring bridge',
    sourceRefs: ['jerrydaphantom-catboost-market-aware', 'HKJC Edge Lab'],
    action: '读取冻结的 CatBoost artifact/report/manifest，输出带 artifact hash、feature policy、training cutoff 的 upcoming-runner SHADOW 概率，并在 Node 侧强制归一化为 PAPER_ONLY。',
    expectedOutcome: '同一场 upcoming race 可安全叠加 market-aware shadow 概率，但现金状态继续保持 NO_BET。',
    automationExecutable: true,
    evidence: [
      'hkjc-horse-model/python/score_market_aware_candidate.py：frozen bundle hash、feature-manifest/report contract、post-time guard 与 JSONL CLI',
      'hkjc-horse-model/src/probability-artifact.js：缺 lineage、重复 runnerId、越界概率、post-time generation 与 promoted flag 全部 fail closed',
      'hkjc-horse-model/src/cli.js shadow-score + hkjc-horse-model/test/shadow-score-cli.test.js：Python scorer 输出先经 validator，再写成 SHADOW / PAPER_ONLY / RESEARCH_ONLY bundle',
      'hkjc-horse-model/src/external-model-comparison.js + app.js：同一场 upcoming race 现已并列展示 heuristic、no-market、live-market baseline 与带 artifact/calibration/training-cutoff lineage 的 shadow market-aware 概率',
    ],
    remaining: ['继续实现 one-cycle race-day cycle，把 due snapshot、shadow score 与已完成的锁单 CLI 串成一次幂等本地周期。'],
  },
  {
    id: 'prospective-lock-ledger',
    priority: 'P5',
    status: 'implemented',
    automationPhase: 'Phase D',
    title: '建立不可变 prospective lock 与三账本结算',
    sourceRefs: ['HKJC Edge Lab', 'Ganyan', 'HKJC Horse-Racing ML Research Platform'],
    action: '在 T-30/T-10/T-3 把模型、价格、组合、原因码和 paper stake 锁进本地 SQLite，赛后按官方派彩自动结算。',
    expectedOutcome: '所有 forward ROI、CLV、slippage、drawdown 与 losing run 只从不可变锁单重算，shadow/paper/cash 不混账。',
    automationExecutable: true,
    evidence: [
      'hkjc-horse-model/src/prospective-locks.js：canonical SHA-256、PAPER_ONLY、pre-post/window guard、WIN/PLACE/QIN/QPL、VOID、CLV、drawdown 与 losing run',
      'hkjc-horse-model/src/sqlite-store.js：append-only prospective_locks，幂等重放与 OPEN 到 SETTLED/VOID 的单次原子转换',
      'hkjc-horse-model/src/cli.js prospective-lock / prospective-settle：本地锁单、官方赛果结算并接入 auto-run',
      'recommendation-audit.js：cash、paper、shadow 独立账本，shadow 锁单永不进入 cash stake',
    ],
    remaining: ['race-day cycle 已接通锁单编排；继续积累真实 2026 forward cohort，现金仍为 NO_BET。'],
  },
  {
    id: 'race-day-cycle',
    priority: 'P6',
    status: 'implemented',
    automationPhase: 'Phase A/D',
    title: '建立有界赛马日周期与本地唤醒配置',
    sourceRefs: ['hkjc-api', 'HKJC Edge Lab'],
    action: '每次只运行一个周期：检查 due window、幂等抓取、验证 shadow 概率、写入不可变锁单，然后退出。',
    expectedOutcome: '只在本地端积累真实 T-30/T-10/T-3 证据，并能审计错过窗口；不把私有数据交给 GitHub。',
    automationExecutable: true,
    evidence: [
      'hkjc-horse-model/src/race-day-cycle.js：单周期、有界重试、post-time guard、零现金锁单与中文摘要',
      'hkjc-horse-model/src/local-scheduler.js：默认禁用、无 secret 的 macOS LaunchAgent 生成器',
      'docs/operations/local-race-day-scheduler.md：演练、审核、安装、日志、备份和卸载手册',
      '本地部署已启用 LaunchAgent（用户明确批准后安装）；每个十分钟周期运行后退出，不是常驻抓取进程。',
    ],
    remaining: [
      '默认 CLI 在未配置冻结 scorer adapter 时只抓取快照；prospective coverage 已能量化 missed/offline/collector-error，下一步积累足量 forward cohort。',
      '现金状态继续 NO_BET；本地调度器不登录、下注或产生非零 cash stake。',
    ],
  },
  {
    id: 'prospective-coverage-gate',
    priority: 'P6',
    status: 'implemented',
    automationPhase: 'Phase D',
    title: '建立 prospective 覆盖率、新鲜度和备份健康闸门',
    sourceRefs: ['HKJC Edge Lab', 'Ganyan'],
    action: '按 meeting/pool/T-window 统计真实快照、锁单和结算覆盖，先声明样本与备份门槛，然后才允许进入 ROI 研究。',
    expectedOutcome: '缺数据会显示精确原因和差额，不把未产生的锁单当成输注，也不允许事后改门槛。',
    automationExecutable: true,
    evidence: [
      'hkjc-horse-model/src/prospective-coverage.js：六类缺口、pool-window 覆盖、新鲜度、备份 checksum 与冻结门槛',
      'hkjc-horse-model/src/cli.js prospective-coverage：从本地 SQLite 产生无路径/无锁单行的聚合报告',
      'dashboard-publish.js：公开端只保留 counts/ratios/dates/reason counts 和闸门差额',
    ],
    remaining: ['工程闸门已完成，但真实数据状态仍是 BLOCKED_DATA；需持续积累 freeze date 之后的全玩法、全窗口锁单和结算。'],
  },
  {
    id: 'prospective-promotion-state-machine',
    priority: 'P7',
    status: 'implemented',
    automationPhase: 'Phase D',
    title: '建立同 cohort 前瞻评估与玩法级晋级状态机',
    sourceRefs: ['HKJC Edge Lab', 'Ganyan', 'jerrydaphantom-catboost-market-aware'],
    action: '只在相同已结算 race-pool cells 上比较候选模型，再按样本、ROI 下界、CLV、校准、回撤、稳定性、收益集中度、placebo 和 lineage 逐项守门。',
    expectedOutcome: 'Research Lab 能解释模型为何 BLOCKED_DATA / NO_GO / REVIEW_REQUIRED；自动化永远不能把候选直接切到现金 PLAY。',
    automationExecutable: true,
    evidence: [
      'hkjc-horse-model/src/prospective-evaluation.js：同 cohort 排除、log loss/Brier/ECE、Top-pick、CLV/ROI、回撤/连败、月度/meeting 稳定性、meeting-block bootstrap 与双 placebo',
      'hkjc-horse-model/src/prospective-promotion.js：WIN/PLACE/QIN/QPL 独立门槛、冻结阈值/血缘和显式 BLOCKED_DATA→NO_GO/RESEARCH_CHAMPION→REVIEW_REQUIRED 状态转换',
      'model-leaderboard.js：只附加相同前瞻 cohort 指标，cashMode 始终为 NO_BET',
    ],
    remaining: [
      '当前真实 forward cohort 仍受 prospective coverage gate 的 BLOCKED_DATA 约束；继续积累 freeze date 后足量已结算锁单。',
      '任何玩法即使通过自动门槛也只到 REVIEW_REQUIRED；人工复核后仍保持 NO_BET，cash PLAY 不在自动状态机内。',
    ],
  },
  {
    id: 'post-gate-feature-staking-experiments',
    priority: 'P8',
    status: 'implemented',
    automationPhase: 'Phase B/D',
    title: '建立同 cohort 特征消融与晋级后仓位实验',
    sourceRefs: ['tianxi-database', 'catowabisabi', 'HKJC Edge Lab', 'Ganyan'],
    action: '冻结 feature policy 后，只在相同 validation/prospective race-runner cohort 比较基础、SpeedPRO、pool money、odds movement 与组合特征；QIN/QPL 和仓位扫描必须先通过各自数据/晋级门槛。',
    expectedOutcome: 'Research Lab 能区分真实增量、缺数据和仅研究仓位曲线，不会把历史正 ROI 或手工批准误当现金授权。',
    automationExecutable: true,
    evidence: [
      'hkjc-horse-model/python/compare_feature_ablations.py：validation-only 选型、完整比赛同 cohort、freeze-date guard、空 prospective fail-closed 与冻结 feature-policy hash',
      'hkjc-horse-model/python/evaluate_exotic_pair_strategy.py：QIN/QPL 需要 T-30/T-10/T-3 verified combination-book coverage，否则在读取 ROI 前返回 BLOCKED_DATA',
      'hkjc-horse-model/src/strategy-risk-report.js：fixed HK$10、0.1/0.25/0.5 Kelly 和 conservative cap 仅在正向 prospective promotion gate 后生成，所有 executable stake 恒为 0',
    ],
    remaining: [
      '工程实验器已完成；仍需真实 timestamped SpeedPRO、pool/odds movement 与足量 fresh forward cohort，才能报告实际增量而不是 fixture 结果。',
      '当前 cashMode 继续 NO_BET；即使候选被人工批准，仓位扫描也不会授权现金 PLAY。',
    ],
  },
  {
    id: 'bayesian-tripwire',
    priority: 'P1',
    status: 'implemented',
    automationPhase: 'Phase C',
    title: '建立 Bayesian skip-gate / confidence trip-wire',
    sourceRefs: ['Ganyan'],
    action: '用最近 90 日信心分布作为 baseline，异常过低时暂停建议，异常过高时提示过拟合/数据漂移风险。',
    expectedOutcome: '前端能显示模型状态异常，避免坏数据日继续下注。',
    automationExecutable: false,
    evidence: [
      'hkjc-horse-model/src/uncertainty-tripwire.js：90 日已结算信心 baseline、shrinkage z-score、分歧/漂移/市场缺口和合法注码降额',
      'buildFinalBetPlan 与 multi-play-portfolio 的现金注码都经过 trip-wire；严重异常 PAPER，中度异常减注',
      'high-disagreement / missing-market / normal-pass / calibration-drift 与 dashboard reason regression tests',
      'app.js 桌面和手机端显示 exact trip-wire summary；旧预算面板明确为 PAPER ONLY。',
    ],
    remaining: ['继续积累 prospective 2026 样本，按滚动校准误差和实际 CLV 调整阈值；当前实现是保守风控，不是盈利保证。'],
  },
  {
    id: 'lightgbm-no-market-benchmark',
    priority: 'P1',
    status: 'implemented',
    automationPhase: 'Phase B',
    title: '复现 no-market LightGBM / LambdaRank benchmark',
    sourceRefs: ['Hongkong-Horse-Racing-Prediction', 'catowabisabi'],
    action: '导出 leakage-safe matrix，训练 no-market tree baseline，评估 log loss、Brier、Top-pick 入前三、QIN/QPL ROI。',
    expectedOutcome: '知道我们的基本面模型是否真的比当前 heuristic 强。',
    automationExecutable: false,
    evidence: [
      'hkjc-horse-model/python/train_tree_model.py',
      'target-aware WIN/PLACE LightGBM tests、versioned predictions 与 strict PLACE settlement benchmark',
    ],
    remaining: ['继续作为 no-market baseline；未经 per-pool ROI/promotion gate 不进入现金推荐。'],
  },
  {
    id: 'parimutuel-stacker-copula-study',
    priority: 'P2',
    status: 'research-only',
    automationPhase: 'Phase B/C',
    title: '研究 parimutuel stacker 与 copula exotic pricing',
    sourceRefs: ['HKJC Benter Engine'],
    action: '只做方法笔记和小样本模拟，不进入现金推荐；重点检查 late-money drift 和 final dividend bias。',
    expectedOutcome: '给未来三重彩/四重彩研究保留方向，但不污染当前保守组合。',
    automationExecutable: false,
    evidence: [
      'docs/research/parimutuel-stacker-copula-notes.md：Harville/Plackett-Luce → Henery/Stern → residual dependence 的独立 benchmark ladder',
      'JonzieLo public-tree audit：无公开数据/账本/测试/LICENSE，README 月度窗口与代码 6MS 不一致，TRI 被排序成无序前三、回测器存在类名断裂',
      '2026 interim-odds research reinforces T-window path dependence and forbids final-price-only promotion',
    ],
    remaining: [
      '等待同一组合的真实 T-30/T-10/T-3/STOP_SELL/CLOSED snapshots、完整 pool coverage 和官方结算，再实现依赖模型。',
      '在独立新鲜 holdout、prospective CLV/ROI、race-cluster uncertainty 和玩法语义测试全部通过前，不进入 cash recommendation，保持 NO_BET。',
    ],
  },
  {
    id: 'j-csc-scraper-schema-audit',
    priority: 'P1',
    status: 'implemented',
    automationPhase: 'Phase B',
    title: '审计 j-csc HKJC 爬虫字段与页面覆盖',
    sourceRefs: ['j-csc/HK-Horse-Racing-Data-Scraper', 'official HKJC racecard and veterinary pages'],
    action: '区分代码证实与 README 声称的页面覆盖，按赛前、赛后、不安全和不可用分类字段，并设计独立 parser fixtures。',
    expectedOutcome: '后续官方解析器补字段时有可测试的覆盖清单，不复制无许可证代码，也不把赛后字段泄漏进训练。',
    automationExecutable: false,
    evidence: [
      'hkjc-horse-model/src/source-coverage-audit.js + source-coverage-audit tests',
      'docs/research/j-csc-scraper-schema-audit.md：固定 commit、许可证边界、字段分类和 synthetic fixture 清单',
      'external-source-registry 将 j-csc 固定为 unknown-license clean-room schema reference，禁止代码和原始数据复用',
    ],
    remaining: ['后续只用自建最小 HTML fixture 实现 racecard/veterinary parser；真实页面需保留 observed_at、checksum、meeting identity 和 post-time guard。'],
  },
];

const EXTERNAL_BENCHMARK_REGISTRY = [
  {
    id: 'catowabisabi-lgb-no-odds-quinella',
    priority: 'P0',
    status: 'partial-blocked-data',
    sourceName: 'catowabisabi/horse-racing-model-training',
    sourceUrl: 'https://github.com/catowabisabi/horse-racing-model-training',
    benchmarkType: 'model-plus-pool-strategy',
    publicMetric: 'LightGBM no-odds top-2 Quinella: 2017 +7.9% ROI, 2018 H1 OOS +2.6% ROI; top-1 pre-race hit about 27%.',
    ourGap: '本地已重放固定 top-2 QIN 与 top-3-box QIN/QPL；validation/holdout 结果为负并维持 NO-BET。缺验证过的 T-30 赔率，尚不能复现 cold-quinella filter。',
    leveragePath: '复用它的实验设计：no-odds LightGBM、严格时间切分、top-2 连赢/QPL replay、cold-quinella filter，不复制结论。',
    requiredLocalData: ['settled races', 'official QIN/QPL dividends', 'leakage-safe no-market training matrix', 'chronological validation/holdout split'],
    promotionGate: '本地 validation 和 holdout 同时优于 current baseline；连赢/QPL ROI 为正；max drawdown 和 profit concentration 合格；不能只靠单场冷门。',
    accessPolicy: 'MIT code; processed parquet and reports can be studied, raw-derived data only local research unless license terms remain safe.',
    localAdoption: 'historical-no-go',
  },
  {
    id: 'jerrydaphantom-catboost-market-aware',
    priority: 'P0',
    status: 'reproduced-no-go',
    sourceName: 'jerrydaphantom/hkjc-ml-research',
    sourceUrl: 'https://github.com/jerrydaphantom/hkjc-ml-research',
    benchmarkType: 'calibrated-market-aware-model',
    publicMetric: 'CatBoost market-aware + sigmoid race normalization: log loss 0.234958, Brier 0.065478, top-pick win rate 32.7%, winner-in-top3 62.1%.',
    ourGap: '同 cohort T-10 market-aware CatBoost 已完成：holdout WIN log loss 0.245335、Top-pick 30.43%，仍弱于其公开 32.7%；全部历史 value candidates 未通过 ROI/稳定性/回撤 gate。',
    leveragePath: '复现 CatBoost/LightGBM market-aware + calibration + model-vs-market threshold grid，并把预测质量和下注 ROI 分开评估。',
    requiredLocalData: ['T-30/T-10/T-3 market odds', 'current/final odds labels separated', 'training dataset market feature flags', 'chronological test split'],
    promotionGate: '预测指标显著优于 baseline，且 EV/probability-gap 过滤后在 holdout 有足够样本和正期望；top-pick-all 不能直接进现金模式。',
    accessPolicy: 'MIT code; public repo lacks raw private scraper/data stack, so methodology only until local replay passes.',
    localAdoption: 'probability-champion-cash-no-bet',
  },
  {
    id: 'anton-no-odds-feature-stack',
    priority: 'P1',
    status: 'reproduce-after-p0',
    sourceName: 'anton-schwarberg/Hongkong-Horse-Racing-Prediction',
    sourceUrl: 'https://github.com/anton-schwarberg/Hongkong-Horse-Racing-Prediction',
    benchmarkType: 'fundamental-feature-stack',
    publicMetric: 'No-odds LGBMClassifier reports ROC-AUC 0.726, Top-1 placed hit 52.9%, Top-3 placed hit 87.1% on held-out future season.',
    ourGap: '我们已有历史滚动特征，但官方 rating、horse weight trend、race-aware percentile ranks、saved live inference artifacts 仍不足。',
    leveragePath: '吸收 feature engineering/persistence 思路，尤其 official rating、target encoding、draw/weight/form normalization 和 live feature path。',
    requiredLocalData: ['race card official rating', 'horse weight trend', 'draw and field-size normalized ranks', 'pre-race feature persistence artifacts'],
    promotionGate: '先作为 PLACE/top3 质量 benchmark；只有本地 win/place calibration 均改善后再影响组合推荐。',
    accessPolicy: 'Public repo; use methodology and feature definitions, do not assume its reported placed-hit metrics equal WIN edge.',
    localAdoption: 'feature-backlog',
  },
  {
    id: 'eprochasson-live-odds-archive',
    priority: 'P1',
    status: 'partially-leveraged',
    sourceName: 'eprochasson/horserace_data',
    sourceUrl: 'https://github.com/eprochasson/horserace_data',
    benchmarkType: 'historical-live-odds-data',
    publicMetric: '2016-2018 live odds archive used by stronger projects; our import matched about 259k rows and created about 6.37M WIN/PLACE snapshots.',
    ourGap: '我们已有 odds snapshots for 1510 races, but no pool snapshots and little 2026 live market coverage.',
    leveragePath: 'Keep imported odds as market-window backtest base, but do not extrapolate 2016-2018 directly to 2026 without current snapshots.',
    requiredLocalData: ['odds_snapshots already imported', 'pool_snapshots missing', 'race id/date/course reconciliation'],
    promotionGate: 'Use only for research and historical market-window replay; cash recommendations require current race-day T-window data.',
    accessPolicy: 'External data archive; keep derived imports local/dashboard-safe, avoid republishing raw archives.',
    localAdoption: 'partial-data',
  },
  {
    id: 'bobosky-rkwyu-live-pool-capture',
    priority: 'P0',
    status: 'data-leverage',
    sourceName: 'Bobosky2005/hkjc-api + rkwyu/sport-betting-data',
    sourceUrl: 'https://github.com/Bobosky2005/hkjc-api',
    secondaryUrl: 'https://github.com/rkwyu/sport-betting-data',
    benchmarkType: 'live-odds-pool-capture',
    publicMetric: 'Public API/scraper references cover HKJC odds and pool investment endpoints for WIN/PLA/QIN/QPL and exotic pools.',
    ourGap: '当前 pool_snapshots = 0；没有 2026 T-30/T-10/T-3 pool money, crowding, takeout-derived features.',
    leveragePath: 'Port endpoint coverage into our normalizer and schedule low-frequency T-window capture instead of inventing endpoint mapping ourselves.',
    requiredLocalData: ['upcoming race schedule', 'live odds endpoint access', 'pool investment endpoint access', 'idempotent SQLite snapshot import'],
    promotionGate: 'Capture must be reliable, idempotent, oddsType-safe, and visible in market coverage report before EV cash gating.',
    accessPolicy: 'Use as implementation references; keep HKJC endpoint behavior fault-tolerant because upstream shape can change.',
    localAdoption: 'data-priority',
  },
  {
    id: 'tianxi-feature-backfill',
    priority: 'P1',
    status: 'data-leverage',
    sourceName: 'sleepingarhat/tianxi-database',
    sourceUrl: 'https://github.com/sleepingarhat/tianxi-database',
    benchmarkType: 'local-only-feature-backfill',
    publicMetric: 'Public description says 2016-2026 HKJC data platform with results, dividends, sectionals, commentary, profiles, trials, entries, and daily audits.',
    ourGap: '我们缺 trials/sectionals/commentary/profile/official-context features that stronger no-odds models use to lift intrinsic signal.',
    leveragePath: 'Build local-only importer for derived features and coverage audit; use it to enrich no-market models without publishing raw third-party rows.',
    requiredLocalData: ['local raw cache outside git', 'schema coverage audit', 'result/dividend reconciliation', 'leakage-safe feature lags'],
    promotionGate: 'Only derived pre-race features enter training; no raw data committed; feature lift must survive chronological holdout.',
    accessPolicy: 'local-only research because no explicit license is confirmed for republishing raw data.',
    localAdoption: 'feature-backlog',
  },
  {
    id: 'j-csc-scraper-schema-audit',
    priority: 'P1',
    status: 'data-leverage',
    sourceName: 'j-csc/HK-Horse-Racing-Data-Scraper',
    sourceUrl: 'https://github.com/j-csc/HK-Horse-Racing-Data-Scraper',
    benchmarkType: 'scraper-schema-audit',
    publicMetric: 'Long-running HKJC scraper reference with horse, racecard, venue, veterinary and related website-page coverage ideas.',
    ourGap: '我们的官方解析链路主要围绕赛果、赛卡、派彩和 odds；兽医记录、排位表细节、页面异常容错和数据源审计仍不完整。',
    leveragePath: '审计它的 HKJC 页面覆盖范围，提炼兽医记录、racecard/排位表、场地和马匹字段，转成我们自己的 parser tests 与 source coverage checklist。',
    requiredLocalData: ['HKJC HTML fixture pages', 'veterinary/racecard field map', 'parser failure fixtures', 'source coverage report'],
    promotionGate: '只把字段覆盖和 parser 测试思路纳入本地；任何原始 scraped data 不进入公开 repo；新增字段必须证明是赛前可得。',
    accessPolicy: 'Research/reference only; GitHub license metadata not machine-readable, so avoid copying code/data into public artifacts.',
    localAdoption: 'schema-audit',
  },
  {
    id: 'jonzielo-parimutuel-copula-study',
    priority: 'P2',
    status: 'research-only-unverified',
    sourceName: 'JonzieLo/hkjc-project',
    sourceUrl: 'https://github.com/JonzieLo/hkjc-project',
    benchmarkType: 'parimutuel-stacker-copula-methodology',
    publicMetric: 'Author-claimed walk-forward ROI +6.63% overall and TRI +35.99% over 799 bets; these figures are not independently reproducible from the public tree.',
    ourGap: 'Public evidence is unverified: no dataset, ledger, tests or LICENSE; README says 25 monthly windows while code uses 6MS windows; exotic price fallback and pool semantics are not promotion-safe.',
    leveragePath: 'Clean-room benchmark Harville/Plackett-Luce first, then independent Henery/Stern order statistics, and only then a shrunk residual-dependence model; preserve ordered TIERCE/TRI separately from unordered TRIO.',
    requiredLocalData: ['complete finishing order and dead-heat/scratch rules', 'pre-race pace and field context', 'same-combination T-window/STOP_SELL/CLOSED prices', 'official pool dividends and prospective locks'],
    promotionGate: 'Ordered TIERCE/TRI and unordered TRIO/QIN/QPL must pass pool-semantic tests, marginal/rank calibration, fresh holdout, race-cluster uncertainty, CLV/slippage and prospective ROI independently.',
    accessPolicy: 'Unknown license: clean-room methodology review only; no code reuse, raw-data import, threshold copying or adoption of headline ROI.',
    localAdoption: 'research-design-only',
  },
];

const STATUS_LABELS = {
  active: '已进入系统',
  next: '下一步学习',
  'research-only': '研究观察',
};

export function buildResearchUpgradeProgram() {
  return {
    version: 'research-led-v2',
    headline: '研究驱动：先学术与开源验证，再进入下注建议。',
    sources: RESEARCH_SOURCES.map((source) => ({ ...source })),
    algorithmBorrowings: ALGORITHM_BORROWINGS.map((item) => ({
      ...item,
      label: STATUS_LABELS[item.status] ?? item.status,
    })),
    followUpActions: FOLLOW_UP_ACTIONS.map((item) => ({ ...item })),
    externalBenchmarkRegistry: EXTERNAL_BENCHMARK_REGISTRY.map((item) => ({ ...item, requiredLocalData: [...item.requiredLocalData] })),
    frontendSignals: [
      '研究升级页签',
      '每项机制显示「已进入系统 / 下一步 / 研究观察」',
      'Research Lab 显示可由每日巡检续跑的 follow-up action 队列',
      'Tier1 外部 benchmark 显示公开强项、我们差距、复现门槛和 adoption 状态',
      '前端解释期望 ROI、概率校准、风险上限，而不只给马号',
      '每日巡检后把模型变化和回测指标一起呈现',
    ],
    guardrail: '只学习公开方法和设计经验，不复制第三方项目代码；所有新机制必须经过本地回测和前端标注后才进入实注建议。',
  };
}

export function summarizeResearchUpgradeProgram(program = buildResearchUpgradeProgram()) {
  const countByStatus = (status) => program.algorithmBorrowings.filter((item) => item.status === status).length;
  const nextItems = program.algorithmBorrowings.filter((item) => item.status === 'next');
  const followUpActions = Array.isArray(program.followUpActions) ? program.followUpActions : [];
  const externalBenchmarkRegistry = Array.isArray(program.externalBenchmarkRegistry) ? program.externalBenchmarkRegistry : [];
  const actionCountByStatus = (status) => followUpActions.filter((item) => item.status === status).length;
  const automationReadyActions = followUpActions.filter((item) => (
    item.automationExecutable
    && ['queued', 'partial'].includes(item.status)
  ));
  const firstAction = automationReadyActions[0];
  const reproductionReadyBenchmarks = externalBenchmarkRegistry.filter((item) => (
    ['reproduce-next', 'reproduce-after-p0'].includes(item.status)
  ));
  const reproducedBenchmarks = externalBenchmarkRegistry.filter((item) => (
    ['partial-blocked-data', 'reproduced-no-go'].includes(item.status)
  ));
  const dataLeverageBenchmarks = externalBenchmarkRegistry
    .filter((item) => item.status === 'data-leverage')
    .sort((a, b) => dataLeverageRank(a.id) - dataLeverageRank(b.id));
  const blockedBenchmarkCount = externalBenchmarkRegistry.filter((item) => (
    item.requiredLocalData.some((data) => /missing|缺|T-30|pool|market/i.test(data))
    || /缺|missing|尚未|pool_snapshots = 0/i.test(item.ourGap)
  )).length;
  const nextBenchmark = reproducedBenchmarks.find((item) => item.status === 'partial-blocked-data')
    ?? reproductionReadyBenchmarks[0]
    ?? externalBenchmarkRegistry.find((item) => item.status === 'data-leverage')
    ?? externalBenchmarkRegistry[0];

  return {
    version: program.version,
    headline: program.headline,
    sourceCount: program.sources.length,
    activeCount: countByStatus('active'),
    nextCount: countByStatus('next'),
    researchOnlyCount: countByStatus('research-only'),
    followUpCount: followUpActions.length,
    implementedActionCount: actionCountByStatus('implemented'),
    partialActionCount: actionCountByStatus('partial'),
    queuedActionCount: actionCountByStatus('queued'),
    researchOnlyActionCount: actionCountByStatus('research-only'),
    automationReadyCount: automationReadyActions.length,
    externalBenchmarkCount: externalBenchmarkRegistry.length,
    reproducedBenchmarkCount: reproducedBenchmarks.length,
    reproductionReadyCount: reproductionReadyBenchmarks.length,
    dataLeverageCount: dataLeverageBenchmarks.length,
    blockedBenchmarkCount,
    tier1GapLabel: '当前模型仍落后 tier1：优先复现外部强 benchmark 后再升级推荐。',
    nextFocus: nextItems.map((item) => item.concept).slice(0, 3).join(' / '),
    nextAction: firstAction ? `${firstAction.priority} ${firstAction.title}` : '暂无排队 action',
    nextBenchmarkAction: nextBenchmark ? `${nextBenchmark.priority} ${nextBenchmark.sourceName}: ${nextBenchmark.leveragePath}` : '暂无外部 benchmark action',
    nextDataLeverageAction: dataLeverageBenchmarks[0]
      ? `${dataLeverageBenchmarks[0].priority} ${dataLeverageBenchmarks[0].sourceName}: ${dataLeverageBenchmarks[0].leveragePath}`
      : '暂无数据 leverage action',
  };
}

function dataLeverageRank(id) {
  const ranks = {
    'tianxi-feature-backfill': 1,
    'bobosky-rkwyu-live-pool-capture': 2,
    'j-csc-scraper-schema-audit': 3,
  };
  return ranks[id] ?? 99;
}
